package db.entities;

public enum Operations {
    SHOW_STUDENTS,
    ADD_STUDENT,
    DELETE_STUDENT,
    SHOW_SUBJECTS,
    ADD_SUBJECT,
    DELETE_SUBJECT,
    COUNT_AVERAGE,
    MODIFY_DATA,
    FIND_STUDENT,
    SHOW_STUDENTS_WITH_GRADES,
    EDIT_STUDENT_GRADE,
    REMOVE_SUBJECT_FOR_STUDENT,
    ADD_SUBJECT_FOR_STUDENT
}
